name: 'Run e2e bench: bench-agent-stream'
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/e2e-bench-agent-stream.yml'
      - 'internal/**'
      - 'apis/grpc/**'
      - 'pkg/agent/ngt/**'
      - 'cmd/agent/ngt/**'
      - 'hack/benchmark/**'
      - 'resources/GO_VERSION'
      - 'resources/NGT_VERSION'
  pull_request:
    paths:
      - '.github/workflows/e2e-bench-agent-stream.yml'
      - 'internal/**'
      - 'apis/grpc/**'
      - 'pkg/agent/ngt/**'
      - 'cmd/agent/ngt/**'
      - 'hack/benchmark/**'
      - 'resources/GO_VERSION'
      - 'resources/NGT_VERSION'

jobs:
  bench-agent-stream:
    name: bench-agent-stream
    runs-on: ubuntu-latest
    container:
      image: vdaas/vald-dataset-container:nightly
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Copy datasets
        run: |
          cp /go/src/github.com/vdaas/vald/`make bench/datasets/hdf5dir/print`/* `make bench/datasets/hdf5dir/print`/
      - name: Run bench-agent-stream
        run: |
          make bench/agent/stream
